#!/usr/bin/env bash
# Script to configure Nginx with custom HTTP response header

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Edit Nginx configuration file to add custom header
sudo sed -i '/server {/a \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
