#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using kill

# Finding the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Checking if the process is running
if [ -n "$pid" ]; then
    echo "Stopping 4-to_infinity_and_beyond process..."
    # Sending SIGTERM signal to the process to gracefully terminate it
    kill "$pid"
else
    echo "4-to_infinity_and_beyond process is not running."
fi
