#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd

# Set IFS to colon (:) to separate fields in /etc/passwd
IFS=":"

# Read each line of /etc/passwd
while read -r username _ uid _ _ homedir shell; do
    # Extract the group id from the username
    group_id=$(echo "$username" | cut -d'-' -f1)
    
    # Extract the password from the password field
    password=$(echo "$_")
    
    # Print the story
    echo "The user $username is part of the $group_id gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
