#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

# Use awk to extract visitor IP and HTTP status code
awk '{print $1, $9}' apache-access.log |
# Sort the data and count occurrences
sort | uniq -c |
# Sort by occurrence number in descending order
sort -rn
